version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/ssl:/etc/nginx/ssl:ro
      # - ./nginx/index.html:/app/html:ro

  gamification-api:
    build: .
    hostname: gamification-api
    container_name: gamification-api
    environment:
      MONGO_URI: ${MONGO_URI}
    env_file:
      - .env
    volumes:
      - .:/app
    # ports:
    #   - "3000:3000"
    depends_on:
      - mongodb
    
  users-api:
    image: rastokopal/factcheckingbe_api
    hostname: users-api
    container_name: users-api
    environment:
      MONGO_URI: ${MONGO_URI}
      NODE_ENV: development
    env_file:
      - .env
    # ports:
    #   - "3001:3000"
    depends_on:
      - mongodb
    command: yarn dev -- -L

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

#   smtp4dev:
#     image: rnwood/smtp4dev:v3
#     restart: always
#     ports:
#       - '5000:5000'
#       - '25:25'
#       - '143:143'
#     volumes:
#       - smtp4dev-data:/smtp4dev
#     environment:
#       - ServerOptions__HostName=${EMAIL_HOST}
#       - RelayOptions__Login=${EMAIL_USERNAME}
#       - RelayOptions__Password=${EMAIL_PASSWORD}

# volumes:
#   smtp4dev-data: