version: "3"

services:
  gamification-api:
    build: .
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

#   smtp4dev:
#     image: rnwood/smtp4dev:v3
#     restart: always
#     ports:
#       - '5000:5000'
#       - '25:25'
#       - '143:143'
#     volumes:
#       - smtp4dev-data:/smtp4dev
#     environment:
#       - ServerOptions__HostName=${EMAIL_HOST}
#       - RelayOptions__Login=${EMAIL_USERNAME}
#       - RelayOptions__Password=${EMAIL_PASSWORD}

# volumes:
#   smtp4dev-data: